# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#

development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: place325
  socket: /tmp/mysql.sock
  database: allthegoods_develop

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: allthegoods
  password: <%= ENV['ALLTHEGOODS_DATABASE_PASSWORD'] %>
  socket: /tmp/mysql.sock
  database: allthegoods_production